version: 2.1
jobs:
  test:
    parameters:
      python_version:
        type: string
    docker:
      - image: circleci/python:<< parameters.python_version >>-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install tox
      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            tox -e unit
          when: always
      - run:
          name: Run integration tests
          command: |
            . venv/bin/activate
            tox -e integration
          when: always
  quality:
    docker:
      - image: circleci/python:2.7.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install tox pylint
      - run:
          name: Run quality tests
          command: |
            . venv/bin/activate
            tox -e quality
          when: always
      - run:
          name: Run python3 quality tests
          command: |
            . venv/bin/activate
            tox -e python3-quality
          when: always
workflows:
  version: 2
  build:
    jobs:
      - test:
          matrix:
            parameters:
              python_version: ["2.7.16", "3.5.7"]
      - quality
