name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - 3.8
        toxenv: [ python3-quality, unit, integration ]
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -U pip wheel
        pip install tox pylint
    - name: Run Quality
      env:
        TOXENV: ${{ matrix.toxenv }}
      if: matrix.toxenv=='python3-quality'
      run: |
          tox -e python3-quality
    - name: Run Unit Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      if: matrix.toxenv=='unit'
      run: tox -e unit
    - name: Run Integration Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      if: matrix.toxenv=='integration'
      run: tox -e integration
